name: flutterweb_yaml
description: A command-line application to generate CI/CD yaml templates.
version: 1.0.0
homepage: https://github.com/MattisBrizard/flutterweb_yaml

environment:
  sdk: '>=2.7.0 <3.0.0'

executable:
  flutterweb_yaml:

dependencies:
  args: ^1.5.2
  mustache: ^1.1.1
  resource: ^2.1.6
  path: ^1.7.0
  yaml: ^2.2.1
